(Imp) Update jest's release version to solve a reported bug
reported issue: https://github.com/facebook/jest/issues/5849
While running: expect.not.arrayContaining
TypeError: Cannot read property 'arrayContaining' of undefined
Updated from version 22.4.3 to 23.0.0-alpha.6r